/**
 * Teams database — 128 national teams
 * code: ISO 3166-1 alpha-2 (lowercase for flagcdn)
 * confederation: FIFA confederation
 * rating: 1-100 overall strength
 */
export const TEAMS = [
  // UEFA (55 teams)
  { name: 'Francia', code: 'fr', confederation: 'UEFA', rating: 93 },
  { name: 'Brasil', code: 'br', confederation: 'CONMEBOL', rating: 92 },
  { name: 'Argentina', code: 'ar', confederation: 'CONMEBOL', rating: 94 },
  { name: 'Inglaterra', code: 'gb-eng', confederation: 'UEFA', rating: 90 },
  { name: 'Espa\u00f1a', code: 'es', confederation: 'UEFA', rating: 91 },
  { name: 'Alemania', code: 'de', confederation: 'UEFA', rating: 88 },
  { name: 'Portugal', code: 'pt', confederation: 'UEFA', rating: 89 },
  { name: 'Pa\u00edses Bajos', code: 'nl', confederation: 'UEFA', rating: 87 },
  { name: 'Italia', code: 'it', confederation: 'UEFA', rating: 86 },
  { name: 'B\u00e9lgica', code: 'be', confederation: 'UEFA', rating: 85 },
  { name: 'Croacia', code: 'hr', confederation: 'UEFA', rating: 84 },
  { name: 'Dinamarca', code: 'dk', confederation: 'UEFA', rating: 80 },
  { name: 'Suiza', code: 'ch', confederation: 'UEFA', rating: 79 },
  { name: 'Colombia', code: 'co', confederation: 'CONMEBOL', rating: 83 },
  { name: 'Uruguay', code: 'uy', confederation: 'CONMEBOL', rating: 82 },
  { name: 'M\u00e9xico', code: 'mx', confederation: 'CONCACAF', rating: 78 },
  { name: 'Estados Unidos', code: 'us', confederation: 'CONCACAF', rating: 79 },
  { name: 'Senegal', code: 'sn', confederation: 'CAF', rating: 78 },
  { name: 'Marruecos', code: 'ma', confederation: 'CAF', rating: 80 },
  { name: 'Jap\u00f3n', code: 'jp', confederation: 'AFC', rating: 78 },
  { name: 'Corea del Sur', code: 'kr', confederation: 'AFC', rating: 76 },
  { name: 'Australia', code: 'au', confederation: 'AFC', rating: 72 },
  { name: 'Ir\u00e1n', code: 'ir', confederation: 'AFC', rating: 74 },
  { name: 'Serbia', code: 'rs', confederation: 'UEFA', rating: 78 },
  { name: 'Polonia', code: 'pl', confederation: 'UEFA', rating: 77 },
  { name: 'Ucrania', code: 'ua', confederation: 'UEFA', rating: 76 },
  { name: 'Austria', code: 'at', confederation: 'UEFA', rating: 76 },
  { name: 'Rep\u00fablica Checa', code: 'cz', confederation: 'UEFA', rating: 75 },
  { name: 'Suecia', code: 'se', confederation: 'UEFA', rating: 76 },
  { name: 'Gales', code: 'gb-wls', confederation: 'UEFA', rating: 72 },
  { name: 'Hungr\u00eda', code: 'hu', confederation: 'UEFA', rating: 73 },
  { name: 'Escocia', code: 'gb-sct', confederation: 'UEFA', rating: 71 },
  { name: 'Turqu\u00eda', code: 'tr', confederation: 'UEFA', rating: 75 },
  { name: 'Rusia', code: 'ru', confederation: 'UEFA', rating: 70 },
  { name: 'Nigeria', code: 'ng', confederation: 'CAF', rating: 76 },
  { name: 'Camer\u00fan', code: 'cm', confederation: 'CAF', rating: 74 },
  { name: 'Ghana', code: 'gh', confederation: 'CAF', rating: 73 },
  { name: 'Argelia', code: 'dz', confederation: 'CAF', rating: 74 },
  { name: 'T\u00fanez', code: 'tn', confederation: 'CAF', rating: 72 },
  { name: 'Egipto', code: 'eg', confederation: 'CAF', rating: 73 },
  { name: 'Costa de Marfil', code: 'ci', confederation: 'CAF', rating: 75 },
  { name: 'Mal\u00ed', code: 'ml', confederation: 'CAF', rating: 68 },
  { name: 'Burkina Faso', code: 'bf', confederation: 'CAF', rating: 66 },
  { name: 'Sud\u00e1frica', code: 'za', confederation: 'CAF', rating: 65 },
  { name: 'R.D. Congo', code: 'cd', confederation: 'CAF', rating: 66 },
  { name: 'Chile', code: 'cl', confederation: 'CONMEBOL', rating: 76 },
  { name: 'Per\u00fa', code: 'pe', confederation: 'CONMEBOL', rating: 73 },
  { name: 'Ecuador', code: 'ec', confederation: 'CONMEBOL', rating: 74 },
  { name: 'Paraguay', code: 'py', confederation: 'CONMEBOL', rating: 70 },
  { name: 'Venezuela', code: 've', confederation: 'CONMEBOL', rating: 68 },
  { name: 'Bolivia', code: 'bo', confederation: 'CONMEBOL', rating: 55 },
  { name: 'Costa Rica', code: 'cr', confederation: 'CONCACAF', rating: 68 },
  { name: 'Canad\u00e1', code: 'ca', confederation: 'CONCACAF', rating: 72 },
  { name: 'Panam\u00e1', code: 'pa', confederation: 'CONCACAF', rating: 64 },
  { name: 'Jamaica', code: 'jm', confederation: 'CONCACAF', rating: 63 },
  { name: 'Honduras', code: 'hn', confederation: 'CONCACAF', rating: 60 },
  { name: 'El Salvador', code: 'sv', confederation: 'CONCACAF', rating: 58 },
  { name: 'Arabia Saudita', code: 'sa', confederation: 'AFC', rating: 70 },
  { name: 'Qatar', code: 'qa', confederation: 'AFC', rating: 65 },
  { name: 'Emiratos \u00c1rabes', code: 'ae', confederation: 'AFC', rating: 62 },
  { name: 'Irak', code: 'iq', confederation: 'AFC', rating: 64 },
  { name: 'Uzbekist\u00e1n', code: 'uz', confederation: 'AFC', rating: 65 },
  { name: 'China', code: 'cn', confederation: 'AFC', rating: 62 },
  { name: 'India', code: 'in', confederation: 'AFC', rating: 55 },
  { name: 'Tailandia', code: 'th', confederation: 'AFC', rating: 55 },
  { name: 'Vietnam', code: 'vn', confederation: 'AFC', rating: 52 },
  { name: 'Noruega', code: 'no', confederation: 'UEFA', rating: 74 },
  { name: 'Rumania', code: 'ro', confederation: 'UEFA', rating: 73 },
  { name: 'Eslovaquia', code: 'sk', confederation: 'UEFA', rating: 71 },
  { name: 'Eslovenia', code: 'si', confederation: 'UEFA', rating: 70 },
  { name: 'Irlanda', code: 'ie', confederation: 'UEFA', rating: 69 },
  { name: 'Finlandia', code: 'fi', confederation: 'UEFA', rating: 68 },
  { name: 'Islandia', code: 'is', confederation: 'UEFA', rating: 67 },
  { name: 'Bosnia', code: 'ba', confederation: 'UEFA', rating: 70 },
  { name: 'Montenegro', code: 'me', confederation: 'UEFA', rating: 65 },
  { name: 'Macedonia del N.', code: 'mk', confederation: 'UEFA', rating: 64 },
  { name: 'Albania', code: 'al', confederation: 'UEFA', rating: 66 },
  { name: 'Georgia', code: 'ge', confederation: 'UEFA', rating: 65 },
  { name: 'Grecia', code: 'gr', confederation: 'UEFA', rating: 72 },
  { name: 'Bulgaria', code: 'bg', confederation: 'UEFA', rating: 63 },
  { name: 'Israel', code: 'il', confederation: 'UEFA', rating: 66 },
  { name: 'Luxemburgo', code: 'lu', confederation: 'UEFA', rating: 52 },
  { name: 'Chipre', code: 'cy', confederation: 'UEFA', rating: 50 },
  { name: 'Bielorrusia', code: 'by', confederation: 'UEFA', rating: 58 },
  { name: 'Cabo Verde', code: 'cv', confederation: 'CAF', rating: 60 },
  { name: 'Mozambique', code: 'mz', confederation: 'CAF', rating: 52 },
  { name: 'Uganda', code: 'ug', confederation: 'CAF', rating: 58 },
  { name: 'Tanzania', code: 'tz', confederation: 'CAF', rating: 55 },
  { name: 'Zambia', code: 'zm', confederation: 'CAF', rating: 57 },
  { name: 'Zimbabue', code: 'zw', confederation: 'CAF', rating: 54 },
  { name: 'Guinea', code: 'gn', confederation: 'CAF', rating: 60 },
  { name: 'Gab\u00f3n', code: 'ga', confederation: 'CAF', rating: 58 },
  { name: 'Benin', code: 'bj', confederation: 'CAF', rating: 56 },
  { name: 'Madagascar', code: 'mg', confederation: 'CAF', rating: 54 },
  { name: 'Namibia', code: 'na', confederation: 'CAF', rating: 52 },
  { name: 'Trinidad y Tobago', code: 'tt', confederation: 'CONCACAF', rating: 56 },
  { name: 'Guatemala', code: 'gt', confederation: 'CONCACAF', rating: 56 },
  { name: 'Curazao', code: 'cw', confederation: 'CONCACAF', rating: 54 },
  { name: 'Hait\u00ed', code: 'ht', confederation: 'CONCACAF', rating: 55 },
  { name: 'Rep. Dominicana', code: 'do', confederation: 'CONCACAF', rating: 50 },
  { name: 'Cuba', code: 'cu', confederation: 'CONCACAF', rating: 48 },
  { name: 'Jord\u00e1n', code: 'jo', confederation: 'AFC', rating: 62 },
  { name: 'Om\u00e1n', code: 'om', confederation: 'AFC', rating: 60 },
  { name: 'Bahr\u00e9in', code: 'bh', confederation: 'AFC', rating: 58 },
  { name: 'Palestina', code: 'ps', confederation: 'AFC', rating: 55 },
  { name: 'Kirguist\u00e1n', code: 'kg', confederation: 'AFC', rating: 52 },
  { name: 'Siria', code: 'sy', confederation: 'AFC', rating: 60 },
  { name: 'Corea del Norte', code: 'kp', confederation: 'AFC', rating: 50 },
  { name: 'Malasia', code: 'my', confederation: 'AFC', rating: 54 },
  { name: 'Indonesia', code: 'id', confederation: 'AFC', rating: 55 },
  { name: 'Nueva Zelanda', code: 'nz', confederation: 'OFC', rating: 62 },
  { name: 'Pap\u00faa N. Guinea', code: 'pg', confederation: 'OFC', rating: 38 },
  { name: 'Nueva Caledonia', code: 'nc', confederation: 'OFC', rating: 40 },
  { name: 'Fiyi', code: 'fj', confederation: 'OFC', rating: 42 },
  { name: 'Islas Salom\u00f3n', code: 'sb', confederation: 'OFC', rating: 38 },
  { name: 'Tahit\u00ed', code: 'pf', confederation: 'OFC', rating: 39 },
  { name: 'Vanuatu', code: 'vu', confederation: 'OFC', rating: 36 },
  { name: 'Samoa', code: 'ws', confederation: 'OFC', rating: 34 },
  { name: 'Tonga', code: 'to', confederation: 'OFC', rating: 30 },
  { name: 'Lituania', code: 'lt', confederation: 'UEFA', rating: 55 },
  { name: 'Letonia', code: 'lv', confederation: 'UEFA', rating: 54 },
  { name: 'Estonia', code: 'ee', confederation: 'UEFA', rating: 53 },
  { name: 'Armenia', code: 'am', confederation: 'UEFA', rating: 60 },
  { name: 'Azerbaiy\u00e1n', code: 'az', confederation: 'UEFA', rating: 55 },
  { name: 'Kazajist\u00e1n', code: 'kz', confederation: 'UEFA', rating: 54 },
  { name: 'Kenia', code: 'ke', confederation: 'CAF', rating: 55 },
  { name: 'Libia', code: 'ly', confederation: 'CAF', rating: 54 },
  { name: 'Togo', code: 'tg', confederation: 'CAF', rating: 56 },
  { name: 'Angola', code: 'ao', confederation: 'CAF', rating: 58 },
  { name: 'Nicaragua', code: 'ni', confederation: 'CONCACAF', rating: 48 },
];

/**
 * Get all teams sorted by rating (descending)
 */
export function getTeamsByRating() {
  return [...TEAMS].sort((a, b) => b.rating - a.rating);
}

/**
 * Find a team by code
 */
export function getTeamByCode(code) {
  return TEAMS.find(t => t.code === code);
}

/**
 * Get teams filtered by confederation
 */
export function getTeamsByConfederation(confederation) {
  return TEAMS.filter(t => t.confederation === confederation);
}
